# place_types.py
# Google Places API types relevant for B2B prospecting, with French labels

PLACE_TYPES = [
    {"label": "Plombier", "value": "plumber"},
    {"label": "Électricien", "value": "electrician"},
    {"label": "Peintre en bâtiment", "value": "painter"},
    {"label": "Couvreur / Toiture", "value": "roofing_contractor"},
    {"label": "Serrurier", "value": "locksmith"},
    {"label": "Déménageur", "value": "moving_company"},
    {"label": "Réparation auto", "value": "car_repair"},
    {"label": "Concessionnaire auto", "value": "car_dealer"},
    {"label": "Lavage auto", "value": "car_wash"},
    {"label": "Comptable", "value": "accounting"},
    {"label": "Avocat", "value": "lawyer"},
    {"label": "Agence immobilière", "value": "real_estate_agency"},
    {"label": "Assurance", "value": "insurance_agency"},
    {"label": "Dentiste", "value": "dentist"},
    {"label": "Médecin", "value": "doctor"},
    {"label": "Kinésithérapeute", "value": "physiotherapist"},
    {"label": "Vétérinaire", "value": "veterinary_care"},
    {"label": "Pharmacie", "value": "pharmacy"},
    {"label": "Salon de coiffure", "value": "hair_care"},
    {"label": "Salon de beauté", "value": "beauty_salon"},
    {"label": "Spa", "value": "spa"},
    {"label": "Salle de sport", "value": "gym"},
    {"label": "Fleuriste", "value": "florist"},
    {"label": "Boulangerie", "value": "bakery"},
    {"label": "Restaurant", "value": "restaurant"},
    {"label": "Café / Bar", "value": "cafe"},
    {"label": "Bar", "value": "bar"},
    {"label": "Bijouterie", "value": "jewelry_store"},
    {"label": "Magasin de vêtements", "value": "clothing_store"},
    {"label": "Magasin de chaussures", "value": "shoe_store"},
    {"label": "Magasin de meubles", "value": "furniture_store"},
    {"label": "Quincaillerie / Bricolage", "value": "hardware_store"},
    {"label": "Magasin d'électronique", "value": "electronics_store"},
    {"label": "Animalerie", "value": "pet_store"},
    {"label": "Librairie", "value": "book_store"},
    {"label": "Magasin de vélos", "value": "bicycle_store"},
    {"label": "Magasin de spiritueux / Caviste", "value": "liquor_store"},
    {"label": "Supérette", "value": "convenience_store"},
    {"label": "Supermarché", "value": "supermarket"},
    {"label": "Pressing / Laverie", "value": "laundry"},
    {"label": "Garde-meuble", "value": "storage"},
    {"label": "Pompes funèbres", "value": "funeral_home"},
    {"label": "Agence de voyage", "value": "travel_agency"},
    {"label": "Galerie d'art", "value": "art_gallery"},
    {"label": "Hébergement / Hôtel", "value": "lodging"},
    {"label": "Bowling", "value": "bowling_alley"},
    {"label": "Camping", "value": "campground"},
    {"label": "Location de voiture", "value": "car_rental"},
    {"label": "Station-service", "value": "gas_station"},
]
